export const currentLoggedInUser = "userCurrentlyLoggedIn"
export const LogoutUser = "LogoutUser"
export const updateUserAnswer = "updateUserAnswer"
export const updateQuestionAnswer = "updateQuestionAnswer"
export const AddNewQuestionModify = "AddNewQuestionModify"
export const AddNewUserModify = "AddNewUserModify"